import type { Metadata } from 'next';
import { ArrowUpRight } from 'lucide-react';
import { PageHero, PageShell } from '@/components/page-parts';

export const metadata: Metadata = { title: 'About Md. Omer Faruque', description: 'Research profile, education, experience, skills, awards and academic contributions of Md. Omer Faruque.' };

export default function AboutPage() {
  const skills = [
    ['Programming', 'Python · MATLAB/Simulink · C'],
    ['AI frameworks', 'Scikit-learn · PyTorch · TensorFlow · Keras'],
    ['Optimization & quantum', 'CVXPY · PennyLane · Qiskit · GUROBI'],
    ['Research tools', 'NumPy · Pandas · Matplotlib · Seaborn · LaTeX'],
    ['Professional practice', 'Teaching · Research writing · Public speaking · Time management'],
  ];
  return (
    <PageShell>
      <PageHero eyebrow="Professional profile" title="Md. Omer Faruque" description="AI researcher, power-systems researcher, quantum machine-learning researcher, research mentor, educator and consultant." aside={<a className="text-link" href="https://drive.google.com/file/d/1Sl3V8dpNnozAG4whzRDWzbhrW_N5uhZK/view" target="_blank" rel="noreferrer">Open full CV <ArrowUpRight size={16} /></a>} />
      <section className="about-profile"><figure><img src="/omer-faruque-portrait.jpg" alt="Portrait of Md. Omer Faruque" /></figure><div><span className="kicker">Research overview</span><h2>Building intelligence around the systems we cannot afford to misunderstand.</h2><p>His research connects renewable-energy forecasting, optimization-embedded deep learning, decision-aware modelling, power-systems cybersecurity and quantum machine learning. Across research, teaching and supervision, the emphasis remains the same: understand the mathematics, reproduce the evidence and make the contribution clear.</p><div className="hero-mini-metrics"><span><strong>360+</strong>Citations</span><span><strong>07</strong>H-index</span><span><strong>13</strong>Publications</span></div></div></section>
      <section className="education-section"><div className="section-heading compact-heading about-left-heading"><span className="kicker">Education</span><h2>Academic foundations</h2></div><article><span>2024 · MSc</span><div><h3>Electrical & Electronic Engineering</h3><p>Dhaka University of Engineering & Technology · CGPA 3.83/4.00</p></div><p>An improved hybrid deep learning model for solar irradiance and on-shore wind power forecasting.</p></article><article><span>2021 · BSc</span><div><h3>Electrical & Electronic Engineering</h3><p>Rajshahi University of Engineering & Technology · CGPA 3.68/4.00</p></div><p>ANN-based maximum power point tracking of a grid-connected photovoltaic solar system.</p></article></section>
      <section className="timeline-section"><div><span className="kicker">Experience</span><h2>A research and teaching continuum.</h2></div><div className="timeline"><article><span>Dec 2025 — Present</span><h3>Lab Mentor & Supervisor</h3><strong>ResearchBuddy AI · Quantum Cyber Intelligence & AI in Power Systems Lab</strong><p>Python, machine learning, deep learning and quantum-ML teaching; full research-lifecycle supervision from topic selection to manuscript preparation.</p></article><article><span>Jul 2023 — May 2025</span><h3>Research Assistant</h3><strong>Dhaka University of Engineering & Technology</strong><p>Deep-learning forecasting, reinforcement learning, algorithm-driven tuning, optimization-embedded architectures and decision-aware models.</p></article><article><span>Aug 2022 — May 2023</span><h3>Lecturer</h3><strong>Bangladesh Army University of Science & Technology</strong><p>Power System Protection, Basic Electronics, Electrical Machines, Control Systems, Renewable Energy and OBE-aligned curriculum development.</p></article></div></section>
      <section className="skills-section"><div className="section-heading compact-heading about-left-heading"><span className="kicker">Capabilities</span><h2>Research stack</h2></div>{skills.map(([group, list], index) => <article key={group}><span>0{index + 1}</span><h3>{group}</h3><p>{list}</p></article>)}</section>
      <section className="milestones-section"><div><span className="kicker">Research milestones</span><h2>Funding & recognition</h2><ul><li><strong>2024</strong> University Grants Commission Research Funding · BDT 120,000</li><li><strong>2023</strong> Vice Chancellor Research Funding · BDT 180,000</li><li><strong>2016</strong> RUET Technical Scholarship</li><li><strong>2010 & 2013</strong> Education Board Scholarships</li></ul></div><div><span className="kicker">Academic contribution</span><h2>Teaching & review</h2><ul><li>YouTube educator · School of EEE</li><li>Reviewer · Electric Power Systems Research</li><li>Reviewer · IEEE Transactions on Applied Superconductivity</li><li>Reviewer · International Journal of Computational Intelligence Systems</li></ul></div></section>
      <section className="gallery-section"><div className="section-heading compact-heading about-left-heading"><span className="kicker">Gallery</span><h2>Beyond the paper</h2></div><div><figure><img src="/omer-faruque-team.webp" alt="Md. Omer Faruque with academic colleagues" /><figcaption>Academic community and collaboration</figcaption></figure><figure><img src="/omer-faruque-beijing.webp" alt="Md. Omer Faruque at Tiananmen Square in Beijing" /><figcaption>International experience · Beijing</figcaption></figure></div></section>
    </PageShell>
  );
}
